server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /start-anonymization {
        proxy_pass http://api:5000/start-anonymization;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /validation_report.html {
        proxy_pass http://api:5000/validation_report.html;
        proxy_set_header Host $host;
    }
}