ALTER SESSION SET CONTAINER = FREEPDB1;
CREATE USER DOMIBUS_ADMIN IDENTIFIED BY "DomibusPass123";
GRANT CREATE SESSION, ALTER SESSION, CONNECT, RESOURCE, DBA TO DOMIBUS_ADMIN;
ALTER USER DOMIBUS_ADMIN QUOTA UNLIMITED ON USERS;
ALTER SESSION SET CURRENT_SCHEMA = DOMIBUS_ADMIN;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml
-- Ran at: 5/05/26 15:08
-- Against: null@offline:oracle?version=11.2.0&changeLogFile=target/liquibase/changelog-1.18.oracle
-- Liquibase version: 4.17.0
-- *********************************************************************

-- Changeset src/main/resources/db/releases/5.1.9/../../common/changelog-before-migration-statements-v2.xml::EDELIVERY-12286_stop_on_error_oracle::Gabriel Maier
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- Changeset src/main/resources/db/releases/5.1.9/../../common/changelog-before-migration-statements-v2.xml::EDELIVERY-12287_assert_previous_migration_succeeded-v2-oracle::Gabriel Maier
create or replace PROCEDURE ASSERT_DB_VERSION_IS(in_expected_versions IN VARCHAR2) AS
    actual_version VARCHAR2(30);
    actual_creation_time TIMESTAMP;
    table_count INT;
    stmt  VARCHAR2(200);
    expected_versions VARCHAR2(50) := in_expected_versions;
BEGIN
    IF expected_versions = 'PreconditionDomibusVersionIs_not_set' OR expected_versions IS NULL THEN
        expected_versions := 'ignore';
    END IF;
    IF expected_versions = 'empty' THEN
        SELECT count(OBJECT_NAME)
        INTO table_count
        FROM USER_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE';
        IF table_count > 0 THEN
                    RAISE_APPLICATION_ERROR(-20002, 'Domibus Failed Assertion Error: The schema should be empty to run this script file');
        END IF;
    ELSE
        IF expected_versions <> 'ignore' THEN
            stmt := 'SELECT V.VERSION, V.CREATION_TIME FROM TB_VERSION V ' ||
                    'INNER JOIN (SELECT MAX(V2.CREATION_TIME) AS MAX_CREATION_TIME FROM TB_VERSION V2) LAST_VERSION ON V.CREATION_TIME = LAST_VERSION.MAX_CREATION_TIME';
            execute IMMEDIATE stmt INTO actual_version, actual_creation_time;
            IF regexp_instr(expected_versions, '(^|,)\s*' || actual_version || '\s*(,|$)') = 0 THEN
                RAISE_APPLICATION_ERROR(-20001, 'Domibus Failed Assertion Error: Please upgrade first to version ' || expected_versions || '. The last successful upgrade was to version ' || actual_version || ' on ' || actual_creation_time);
            END IF;
        END IF;
    END IF;
END ASSERT_DB_VERSION_IS;
/

CALL ASSERT_DB_VERSION_IS('empty');
/

/* Call this stored procedure to execute the statement contained in the parameter dmlStatement.
 In case the execution causes an error the statement that failed is rolled back.
 If the SQLCODE equals oraErrorCode then a warning message is logged and the error is ignored otherwise the error is rethrown with the SQLCODE code -20003  */
CREATE OR REPLACE PROCEDURE EXECUTE_AND_IGNORE_ERROR(dmlStatement IN VARCHAR2, oraErrorCode IN NUMBER) AS
BEGIN
    EXECUTE IMMEDIATE dmlStatement;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = oraErrorCode THEN
                DBMS_OUTPUT.PUT_LINE('Warning: Ignoring error [' || SQLERRM || '] after executing [' || dmlStatement || ']');
            ELSE
                RAISE_APPLICATION_ERROR(-20003, 'Unhandled exception [' || SQLERRM || ']');
            END IF;
END EXECUTE_AND_IGNORE_ERROR;
/

/* Extract the date from a tsid */
CREATE OR REPLACE FUNCTION tsid_to_date(tsid IN NUMBER)
    RETURN TIMESTAMP IS
    date_component NUMBER;
BEGIN
    SELECT MOD(FLOOR(tsid / POWER(2, 22)), POWER(2, 64)) AS unsigned_shifted INTO date_component FROM dual;
    -- Return the milliseconds that have passed since the default TSID epoch (midnight on 1st of January 2020)
    RETURN TIMESTAMP '2020-01-01 00:00:00.000' + NUMTODSINTERVAL(date_component / 1000, 'SECOND');
END;
/

/* Return 1 if TB_USER_MESSAGE is partitioned; 0 otherwise */
CREATE OR REPLACE FUNCTION is_partitioned
    RETURN NUMBER IS
    v_partitioned VARCHAR2(3);
BEGIN
    BEGIN
        SELECT partitioned
        INTO v_partitioned
        FROM user_tables
        WHERE table_name = 'TB_USER_MESSAGE';

        IF v_partitioned = 'YES' THEN
            RETURN 1;
        ELSE
            RETURN 0;
        END IF;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                -- Table doesn't exist or no access
                RETURN 0;
            WHEN TOO_MANY_ROWS THEN
                -- This shouldn't happen
                RETURN 0;
    END;
END is_partitioned;
/

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-oracle sequence::martifp,Cosmin Baciu
-- create HIBERNATE_SEQUENCE
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 100 INCREMENT BY 20 MINVALUE 1 CACHE 1000 NOORDER;

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7836::idragusa
-- create DOMIBUS_SCALABLE_SEQUENCE sequence
-- TODO SCALE EXTEND
CREATE SEQUENCE DOMIBUS_SCALABLE_SEQUENCE START WITH 50 INCREMENT BY 50 MINVALUE 50 MAXVALUE 9999999999 CACHE 1000 CYCLE NOORDER;

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog-quartz.xml::EDELIVERY-3425::migueti
CREATE TABLE QRTZ_BLOB_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, BLOB_DATA BLOB);

CREATE TABLE QRTZ_CALENDARS (SCHED_NAME VARCHAR2(120) NOT NULL, CALENDAR_NAME VARCHAR2(200) NOT NULL, CALENDAR_BLOB BLOB NOT NULL);

CREATE TABLE QRTZ_CRON_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, CRON_EXPRESSION VARCHAR2(120) NOT NULL, TIME_ZONE_ID VARCHAR2(80));

CREATE TABLE QRTZ_FIRED_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, ENTRY_ID VARCHAR2(95) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, FIRED_TIME NUMBER(38, 0) NOT NULL, SCHED_TIME NUMBER(38, 0) NOT NULL, PRIORITY INTEGER NOT NULL, STATE VARCHAR2(16) NOT NULL, JOB_NAME VARCHAR2(200), JOB_GROUP VARCHAR2(200), IS_NONCONCURRENT NUMBER(1), REQUESTS_RECOVERY NUMBER(1));

CREATE TABLE QRTZ_JOB_DETAILS (SCHED_NAME VARCHAR2(120) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250), JOB_CLASS_NAME VARCHAR2(250) NOT NULL, IS_DURABLE NUMBER(1) NOT NULL, IS_NONCONCURRENT NUMBER(1) NOT NULL, IS_UPDATE_DATA NUMBER(1) NOT NULL, REQUESTS_RECOVERY NUMBER(1) NOT NULL, JOB_DATA BLOB);

CREATE TABLE QRTZ_LOCKS (SCHED_NAME VARCHAR2(120) NOT NULL, LOCK_NAME VARCHAR2(40) NOT NULL);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL);

CREATE TABLE QRTZ_SCHEDULER_STATE (SCHED_NAME VARCHAR2(120) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, LAST_CHECKIN_TIME NUMBER(38, 0) NOT NULL, CHECKIN_INTERVAL NUMBER(38, 0) NOT NULL);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, REPEAT_COUNT NUMBER(38, 0) NOT NULL, REPEAT_INTERVAL NUMBER(38, 0) NOT NULL, TIMES_TRIGGERED NUMBER(38, 0) NOT NULL);

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, STR_PROP_1 VARCHAR2(512), STR_PROP_2 VARCHAR2(512), STR_PROP_3 VARCHAR2(512), INT_PROP_1 INTEGER, INT_PROP_2 INTEGER, LONG_PROP_1 NUMBER(38, 0), LONG_PROP_2 NUMBER(38, 0), DEC_PROP_1 DECIMAL(13, 4), DEC_PROP_2 DECIMAL(13, 4), BOOL_PROP_1 NUMBER(1), BOOL_PROP_2 NUMBER(1));

CREATE TABLE QRTZ_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250), NEXT_FIRE_TIME NUMBER(38, 0), PREV_FIRE_TIME NUMBER(38, 0), PRIORITY INTEGER, TRIGGER_STATE VARCHAR2(16) NOT NULL, TRIGGER_TYPE VARCHAR2(8) NOT NULL, START_TIME NUMBER(38, 0) NOT NULL, END_TIME NUMBER(38, 0), CALENDAR_NAME VARCHAR2(200), MISFIRE_INSTR NUMBER(5), JOB_DATA BLOB);

ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT PRIMARY_01 PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_CALENDARS ADD CONSTRAINT PRIMARY_02 PRIMARY KEY (SCHED_NAME, CALENDAR_NAME);

ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT PRIMARY_03 PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_FIRED_TRIGGERS ADD CONSTRAINT PRIMARY_04 PRIMARY KEY (SCHED_NAME, ENTRY_ID);

ALTER TABLE QRTZ_JOB_DETAILS ADD CONSTRAINT PRIMARY_05 PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP);

ALTER TABLE QRTZ_LOCKS ADD CONSTRAINT PRIMARY_06 PRIMARY KEY (SCHED_NAME, LOCK_NAME);

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS ADD CONSTRAINT PRIMARY_07 PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_SCHEDULER_STATE ADD CONSTRAINT PRIMARY_08 PRIMARY KEY (SCHED_NAME, INSTANCE_NAME, LAST_CHECKIN_TIME, CHECKIN_INTERVAL);

ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT PRIMARY_09 PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT PRIMARY_10 PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT PRIMARY_11 PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME);

CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME, REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME, CALENDAR_NAME);

CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE);

ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_BLOB_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_CRON_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_SIMPLE_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_SIMPROP_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT FK_TRIGGERS FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-4740::idragusa
-- Plugin specific tables
CREATE TABLE WS_PLUGIN_TB_MESSAGE_LOG (ID_PK NUMBER(38, 0) NOT NULL, MESSAGE_ID VARCHAR2(255) NOT NULL, CONVERSATION_ID VARCHAR2(255), REF_TO_MESSAGE_ID VARCHAR2(255), FROM_PARTY_ID VARCHAR2(255), FINAL_RECIPIENT VARCHAR2(255), ORIGINAL_SENDER VARCHAR2(255), RECEIVED TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT PK_WS_PLUGIN_TB_MESSAGE_LOG PRIMARY KEY (ID_PK));

ALTER TABLE WS_PLUGIN_TB_MESSAGE_LOG ADD CONSTRAINT UK_WS_MESSAGE_ID UNIQUE (MESSAGE_ID);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-2427::Francois Gautier
-- WS Plugin specific tables for backend dispatch
CREATE TABLE WS_PLUGIN_TB_BACKEND_MSG_LOG (ID_PK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), MESSAGE_ID VARCHAR2(255) NOT NULL, MESSAGE_IDS CLOB, MESSAGE_ENTITY_ID NUMBER(38, 0) NOT NULL, FINAL_RECIPIENT VARCHAR2(255), ORIGINAL_SENDER VARCHAR2(255), BACKEND_MESSAGE_STATUS VARCHAR2(255), MESSAGE_STATUS VARCHAR2(255), BACKEND_MESSAGE_TYPE VARCHAR2(255), RULE_NAME VARCHAR2(255), SENT TIMESTAMP NOT NULL, FAILED TIMESTAMP, SEND_ATTEMPTS INTEGER, SEND_ATTEMPTS_MAX INTEGER, NEXT_ATTEMPT TIMESTAMP, SCHEDULED NUMBER(1), CONSTRAINT PK_WS_PLUGIN_BACKEND_MSG_LOG PRIMARY KEY (ID_PK));

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.RULE_NAME IS 'Name of the rule used for dispatching';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.SENT IS 'DateTime when the message had been dispatched';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.FAILED IS 'DateTime when the message had failed';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.SEND_ATTEMPTS IS 'Number of attempts sent';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.SEND_ATTEMPTS_MAX IS 'Number of attempts maximal';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.NEXT_ATTEMPT IS 'DateTime for the next attempt';

COMMENT ON COLUMN WS_PLUGIN_TB_BACKEND_MSG_LOG.SCHEDULED IS 'true if the backend message is already scheduled to be sent';

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-Dictionary Tables::Cosmin Baciu
CREATE TABLE TB_D_MSH_ROLE (ID_PK NUMBER(38, 0) NOT NULL, ROLE VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_MSH_ROLE PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_MSH_ROLE ADD CONSTRAINT UK_D_MSH_ROLE UNIQUE (ROLE);

CREATE TABLE TB_D_MESSAGE_PROPERTY (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255) NOT NULL, VALUE VARCHAR2(1024), TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_MSG_PROPERTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_MESSAGE_PROPERTY ADD CONSTRAINT UK_D_MSG_PROP_NAME UNIQUE (NAME, VALUE, TYPE);

CREATE TABLE TB_D_PART_PROPERTY (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255) NOT NULL, VALUE VARCHAR2(1024), TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_PART_PROPERTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_PART_PROPERTY ADD CONSTRAINT UK_D_PART_PROP_NAME UNIQUE (NAME, VALUE, TYPE);

CREATE TABLE TB_D_MPC (ID_PK NUMBER(38, 0) NOT NULL, VALUE VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_MPC PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_MPC ADD CONSTRAINT UK_D_MPC_VALUE UNIQUE (VALUE);

CREATE TABLE TB_D_SERVICE (ID_PK NUMBER(38, 0) NOT NULL, VALUE VARCHAR2(255) NOT NULL, TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_SERVICE PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_SERVICE ADD CONSTRAINT UK_D_SERVICE_VALUE_TYPE UNIQUE (VALUE, TYPE);

CREATE TABLE TB_D_PARTY (ID_PK NUMBER(38, 0) NOT NULL, VALUE VARCHAR2(255) NOT NULL, TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_PARTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_PARTY ADD CONSTRAINT UK_D_PARTY_VALUE_TYPE UNIQUE (VALUE, TYPE);

CREATE TABLE TB_D_ACTION (ID_PK NUMBER(38, 0) NOT NULL, ACTION VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_ACTION PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_ACTION ADD CONSTRAINT UK_D_PARTY_ACTION UNIQUE (ACTION);

CREATE TABLE TB_D_AGREEMENT (ID_PK NUMBER(38, 0) NOT NULL, VALUE VARCHAR2(255) NOT NULL, TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_AGREEMENT PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_AGREEMENT ADD CONSTRAINT UK_D_AGREEMENT_VALUE_TYPE UNIQUE (VALUE, TYPE);

CREATE TABLE TB_D_ROLE (ID_PK NUMBER(38, 0) NOT NULL, ROLE VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_ROLE PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_ROLE ADD CONSTRAINT UK_D_ROLE_VALUE UNIQUE (ROLE);

CREATE TABLE TB_D_NOTIFICATION_STATUS (ID_PK NUMBER(38, 0) NOT NULL, STATUS VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_NOTIFICATION_STATUS PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_NOTIFICATION_STATUS ADD CONSTRAINT UK_D_NOTIF_STATUS UNIQUE (STATUS);

CREATE TABLE TB_D_MESSAGE_STATUS (ID_PK NUMBER(38, 0) NOT NULL, STATUS VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_MESSAGE_STATUS PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_MESSAGE_STATUS ADD CONSTRAINT UK_D_MESSAGE_STATUS UNIQUE (STATUS);

CREATE TABLE TB_D_TIMEZONE_OFFSET (ID_PK NUMBER(38, 0) NOT NULL, NEXT_ATTEMPT_TIMEZONE_ID VARCHAR2(255), NEXT_ATTEMPT_OFFSET_SECONDS INTEGER, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_D_TIMEZONE_OFFSET PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_D_TIMEZONE_OFFSET.NEXT_ATTEMPT_TIMEZONE_ID IS 'Time zone ID on the application server to use when converting the next attempt for displaying it to the user';

COMMENT ON COLUMN TB_D_TIMEZONE_OFFSET.NEXT_ATTEMPT_OFFSET_SECONDS IS 'Offset in seconds of the time zone on the application server to use when converting the next attempt for displaying it to the user';

ALTER TABLE TB_D_TIMEZONE_OFFSET ADD CONSTRAINT UK_D_TIMEZONE_OFFSET UNIQUE (NEXT_ATTEMPT_TIMEZONE_ID, NEXT_ATTEMPT_OFFSET_SECONDS);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-UserMessage Tables::Cosmin Baciu
CREATE TABLE TB_USER_MESSAGE (ID_PK NUMBER(38, 0) NOT NULL, MESSAGE_ID VARCHAR2(255), MSH_ROLE_ID_FK NUMBER(38, 0) NOT NULL, REF_TO_MESSAGE_ID VARCHAR2(255), CONVERSATION_ID VARCHAR2(255), SOURCE_MESSAGE NUMBER(1), MESSAGE_FRAGMENT NUMBER(1), TEST_MESSAGE NUMBER(1), EBMS3_TIMESTAMP TIMESTAMP, ACTION_ID_FK NUMBER(38, 0), AGREEMENT_ID_FK NUMBER(38, 0), SERVICE_ID_FK NUMBER(38, 0), MPC_ID_FK NUMBER(38, 0), FROM_PARTY_ID_FK NUMBER(38, 0), FROM_ROLE_ID_FK NUMBER(38, 0), TO_PARTY_ID_FK NUMBER(38, 0), TO_ROLE_ID_FK NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_USER_MESSAGE PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_USER_MESSAGE.SOURCE_MESSAGE IS 'true if the message is a SourceMessage';

COMMENT ON COLUMN TB_USER_MESSAGE.MESSAGE_FRAGMENT IS 'true if the message is a message fragment';

COMMENT ON COLUMN TB_USER_MESSAGE.EBMS3_TIMESTAMP IS 'the EBMS3 timestamp present in eb:Messaging/eb:UserMessage/eb:MessageInfo/eb:Timestamp';

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_ACTION_ID FOREIGN KEY (ACTION_ID_FK) REFERENCES TB_D_ACTION (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_AGREEMENT_ID FOREIGN KEY (AGREEMENT_ID_FK) REFERENCES TB_D_AGREEMENT (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_SERVICE_ID FOREIGN KEY (SERVICE_ID_FK) REFERENCES TB_D_SERVICE (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_MPC_ID FOREIGN KEY (MPC_ID_FK) REFERENCES TB_D_MPC (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_FROM_PARTY_ID FOREIGN KEY (FROM_PARTY_ID_FK) REFERENCES TB_D_PARTY (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_FROM_ROLE_ID FOREIGN KEY (FROM_ROLE_ID_FK) REFERENCES TB_D_ROLE (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_TO_PARTY_ID FOREIGN KEY (TO_PARTY_ID_FK) REFERENCES TB_D_PARTY (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_TO_ROLE_ID FOREIGN KEY (TO_ROLE_ID_FK) REFERENCES TB_D_ROLE (ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

CREATE INDEX IDX_USER_MSG_MESSAGE_ID ON TB_USER_MESSAGE(MESSAGE_ID);

CREATE INDEX IDX_USER_MSG_ACTION_ID ON TB_USER_MESSAGE(ACTION_ID_FK);

CREATE INDEX IDX_USER_MSG_AGREEMENT_ID ON TB_USER_MESSAGE(AGREEMENT_ID_FK);

CREATE INDEX IDX_USER_MSG_SERVICE_ID ON TB_USER_MESSAGE(SERVICE_ID_FK);

CREATE INDEX IDX_USER_MSG_MPC_ID ON TB_USER_MESSAGE(MPC_ID_FK);

CREATE INDEX IDX_USER_MSG_FROM_PARTY_ID ON TB_USER_MESSAGE(FROM_PARTY_ID_FK);

CREATE INDEX IDX_FROM_ROLE_ID ON TB_USER_MESSAGE(FROM_ROLE_ID_FK);

CREATE INDEX IDX_USER_MSG_TO_PARTY_ID ON TB_USER_MESSAGE(TO_PARTY_ID_FK);

CREATE INDEX IDX_TO_ROLE_ID ON TB_USER_MESSAGE(TO_ROLE_ID_FK);

CREATE INDEX IDX_TEST_MESSAGE ON TB_USER_MESSAGE(TEST_MESSAGE, ID_PK);

CREATE INDEX IDX_UM_DELETION_COMPOSITE ON TB_USER_MESSAGE(MPC_ID_FK, ID_PK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT UK_USER_MSG_MESSAGE_ID UNIQUE (MESSAGE_ID, MSH_ROLE_ID_FK);

CREATE TABLE TB_MESSAGE_ACKNW (ID_PK NUMBER(38, 0) NOT NULL, FROM_VALUE VARCHAR2(255), TO_VALUE VARCHAR2(255), ACKNOWLEDGE_DATE TIMESTAMP, USER_MESSAGE_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_MESSAGE_ACKNW PRIMARY KEY (ID_PK));

ALTER TABLE TB_MESSAGE_ACKNW ADD CONSTRAINT FK_MSG_ACK_USER_MSG FOREIGN KEY (USER_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK);

CREATE INDEX IDX_MSG_ACKNW_MESSAGE_ID_FK ON TB_MESSAGE_ACKNW(USER_MESSAGE_ID_FK);

CREATE TABLE TB_MESSAGE_ACKNW_PROP (ID_PK NUMBER(38, 0) NOT NULL, PROPERTY_NAME VARCHAR2(255), PROPERTY_VALUE VARCHAR2(255), MESSAGE_ACK_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_MESSAGE_ACKNW_PROP PRIMARY KEY (ID_PK));

ALTER TABLE TB_MESSAGE_ACKNW_PROP ADD CONSTRAINT FK_MSG_ACK_PROP_MSG_ACK FOREIGN KEY (MESSAGE_ACK_ID_FK) REFERENCES TB_MESSAGE_ACKNW (ID_PK);

CREATE INDEX IDX_MSG_ACK_PROP_MSG_ACK ON TB_MESSAGE_ACKNW_PROP(MESSAGE_ACK_ID_FK);

CREATE TABLE TB_SJ_MESSAGE_HEADER (ID_PK NUMBER(38, 0) NOT NULL, BOUNDARY VARCHAR2(255), START_MULTIPART VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SJ_MESSAGE_HEADER PRIMARY KEY (ID_PK));

COMMENT ON TABLE TB_SJ_MESSAGE_HEADER IS 'Stores the message header details for SplitAndJoin';

COMMENT ON COLUMN TB_SJ_MESSAGE_HEADER.BOUNDARY IS 'The multipart boundary value';

COMMENT ON COLUMN TB_SJ_MESSAGE_HEADER.START_MULTIPART IS 'The multipart start value';

CREATE TABLE TB_SJ_MESSAGE_GROUP (ID_PK NUMBER(38, 0) NOT NULL, GROUP_ID VARCHAR2(255) NOT NULL, MESSAGE_SIZE NUMBER(38, 0), FRAGMENT_COUNT INTEGER, SENT_FRAGMENTS INTEGER, RECEIVED_FRAGMENTS INTEGER, COMPRESSION_ALGORITHM VARCHAR2(255), COMPRESSED_MESSAGE_SIZE NUMBER(38, 0), SOAP_ACTION VARCHAR2(255), REJECTED NUMBER(1), EXPIRED NUMBER(1), MSH_ROLE_ID_FK NUMBER(38, 0) NOT NULL, SOURCE_MESSAGE_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SJ_MESSAGE_GROUP PRIMARY KEY (ID_PK));

COMMENT ON TABLE TB_SJ_MESSAGE_GROUP IS 'Stores information about the message group for SplitAndJoin';

COMMENT ON COLUMN TB_SJ_MESSAGE_GROUP.MESSAGE_SIZE IS 'The message size before compression';

COMMENT ON COLUMN TB_SJ_MESSAGE_GROUP.COMPRESSED_MESSAGE_SIZE IS 'The size of the message after compression';

COMMENT ON COLUMN TB_SJ_MESSAGE_GROUP.REJECTED IS 'True if the message group has been rejected';

COMMENT ON COLUMN TB_SJ_MESSAGE_GROUP.EXPIRED IS 'True if the message group has expired';

ALTER TABLE TB_SJ_MESSAGE_GROUP ADD CONSTRAINT FK_MSG_FG_GROUP_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

ALTER TABLE TB_SJ_MESSAGE_GROUP ADD CONSTRAINT FK_MSG_FG_GROUP_UM FOREIGN KEY (SOURCE_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK);

ALTER TABLE TB_SJ_MESSAGE_GROUP ADD CONSTRAINT FK_MSG_FG_GROUP_MH FOREIGN KEY (ID_PK) REFERENCES TB_SJ_MESSAGE_HEADER (ID_PK);

CREATE INDEX IDX_SJ_MG_SM_ID_FK ON TB_SJ_MESSAGE_GROUP(SOURCE_MESSAGE_ID_FK);

CREATE INDEX IDX_SJ_MG_ROLE_FK ON TB_SJ_MESSAGE_GROUP(MSH_ROLE_ID_FK);

CREATE TABLE TB_SJ_MESSAGE_FRAGMENT (ID_PK NUMBER(38, 0) NOT NULL, FRAGMENT_NUMBER INTEGER NOT NULL, GROUP_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_MESSAGE_FRAGMENT PRIMARY KEY (ID_PK));

ALTER TABLE TB_SJ_MESSAGE_FRAGMENT ADD CONSTRAINT FK_SJ_MSG_FG_GROUP FOREIGN KEY (GROUP_ID_FK) REFERENCES TB_SJ_MESSAGE_GROUP (ID_PK);

ALTER TABLE TB_SJ_MESSAGE_FRAGMENT ADD CONSTRAINT FK_SJ_MSG_FG_USER_MSG FOREIGN KEY (ID_PK) REFERENCES TB_USER_MESSAGE (ID_PK);

CREATE INDEX IDX_FK_SJ_MSG_FG_GROUP ON TB_SJ_MESSAGE_FRAGMENT(GROUP_ID_FK);

CREATE TABLE TB_USER_MESSAGE_LOG (ID_PK NUMBER(38, 0) NOT NULL, BACKEND VARCHAR2(255), RECEIVED TIMESTAMP NOT NULL, ACKNOWLEDGED TIMESTAMP, DOWNLOADED TIMESTAMP, ARCHIVED TIMESTAMP, EXPORTED TIMESTAMP, FAILED TIMESTAMP, RESTORED TIMESTAMP, DELETED TIMESTAMP, NEXT_ATTEMPT TIMESTAMP, FK_TIMEZONE_OFFSET NUMBER(38, 0), SEND_ATTEMPTS INTEGER, SEND_ATTEMPTS_MAX INTEGER, SCHEDULED NUMBER(1), VERSION INTEGER DEFAULT 0 NOT NULL, MESSAGE_STATUS_ID_FK NUMBER(38, 0) NOT NULL, MSH_ROLE_ID_FK NUMBER(38, 0) NOT NULL, NOTIFICATION_STATUS_ID_FK NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), PROCESSING_TYPE VARCHAR2(255), CONSTRAINT PK_MESSAGE_LOG PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_USER_MESSAGE_LOG.SCHEDULED IS 'true if the message is already scheduled to be sent';

COMMENT ON COLUMN TB_USER_MESSAGE_LOG.VERSION IS 'Used for optimistic locking mechanism';

ALTER TABLE TB_USER_MESSAGE_LOG ADD CONSTRAINT FK_MSG_LOG_MSG_STATUS FOREIGN KEY (MESSAGE_STATUS_ID_FK) REFERENCES TB_D_MESSAGE_STATUS (ID_PK);

ALTER TABLE TB_USER_MESSAGE_LOG ADD CONSTRAINT FK_MSG_LOG_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

ALTER TABLE TB_USER_MESSAGE_LOG ADD CONSTRAINT FK_MSG_LOG_NOTIF_STATUS FOREIGN KEY (NOTIFICATION_STATUS_ID_FK) REFERENCES TB_D_NOTIFICATION_STATUS (ID_PK);

ALTER TABLE TB_USER_MESSAGE_LOG ADD CONSTRAINT FK_MSG_LOG_MSG_ID FOREIGN KEY (ID_PK) REFERENCES TB_USER_MESSAGE (ID_PK);

ALTER TABLE TB_USER_MESSAGE_LOG ADD CONSTRAINT FK_MESSAGE_LOG_TZ_OFFSET FOREIGN KEY (FK_TIMEZONE_OFFSET) REFERENCES TB_D_TIMEZONE_OFFSET (ID_PK);

CREATE INDEX IDX_MESSAGE_LOG_MSG_STATUS_ID ON TB_USER_MESSAGE_LOG(MESSAGE_STATUS_ID_FK);

CREATE INDEX IDX_MESSAGE_LOG_MSG_ROLE_ID ON TB_USER_MESSAGE_LOG(MSH_ROLE_ID_FK);

CREATE INDEX IDX_MSG_LOG_NOTIF_STATUS_ID ON TB_USER_MESSAGE_LOG(NOTIFICATION_STATUS_ID_FK);

CREATE INDEX IDX_USER_LOG_RECEIVED ON TB_USER_MESSAGE_LOG(RECEIVED);

CREATE INDEX IDX_MESSAGE_LOG_TZ_OFFSET ON TB_USER_MESSAGE_LOG(FK_TIMEZONE_OFFSET);

CREATE INDEX IDX_MSG_ARCHIVED ON TB_USER_MESSAGE_LOG(ARCHIVED);

CREATE INDEX IDX_MSG_EXPORTED ON TB_USER_MESSAGE_LOG(EXPORTED);

CREATE INDEX IDX_MSG_ACKNOWLEDGED ON TB_USER_MESSAGE_LOG(ACKNOWLEDGED);

CREATE INDEX IDX_MSG_PROCESSING_TYPE ON TB_USER_MESSAGE_LOG(PROCESSING_TYPE);

CREATE INDEX IDX_MSG_DOWNLOADED ON TB_USER_MESSAGE_LOG(DOWNLOADED);

CREATE INDEX IDX_UML_DELETION_COMPOSITE ON TB_USER_MESSAGE_LOG(DOWNLOADED, ID_PK, MESSAGE_STATUS_ID_FK);

CREATE TABLE TB_MESSAGING_LOCK (ID_PK NUMBER(38, 0) NOT NULL, MESSAGE_TYPE VARCHAR2(10), MESSAGE_RECEIVED TIMESTAMP, MESSAGE_STATE VARCHAR2(10), MESSAGE_ID VARCHAR2(255), INITIATOR VARCHAR2(255), MPC VARCHAR2(255), SEND_ATTEMPTS INTEGER, SEND_ATTEMPTS_MAX INTEGER, NEXT_ATTEMPT TIMESTAMP, FK_TIMEZONE_OFFSET NUMBER(38, 0), MESSAGE_STALED TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_MESSAGING_LOCK PRIMARY KEY (ID_PK));

ALTER TABLE TB_MESSAGING_LOCK ADD CONSTRAINT FK_MESSAGING_LOCK_TZ_OFFSET FOREIGN KEY (FK_TIMEZONE_OFFSET) REFERENCES TB_D_TIMEZONE_OFFSET (ID_PK);

CREATE INDEX IDX_MESSAGE_LOCK_SEARCH ON TB_MESSAGING_LOCK(INITIATOR, MPC, MESSAGE_STATE, NEXT_ATTEMPT);

CREATE INDEX IDX_MESSAGE_LOCK_INIT ON TB_MESSAGING_LOCK(INITIATOR);

CREATE INDEX IDX_MESSAGE_LOCK_STATE ON TB_MESSAGING_LOCK(MESSAGE_STATE);

CREATE UNIQUE INDEX IDX_MESSAGE_LOCK_UNIQUE_ID ON TB_MESSAGING_LOCK(MESSAGE_ID);

CREATE INDEX IDX_MESSAGING_LOCK_TZ_OFFSET ON TB_MESSAGING_LOCK(FK_TIMEZONE_OFFSET);

CREATE TABLE TB_PART_INFO (ID_PK NUMBER(38, 0) NOT NULL, BINARY_DATA BLOB, DESCRIPTION_LANG VARCHAR2(255), DESCRIPTION_VALUE VARCHAR2(255), HREF VARCHAR2(255), IN_BODY NUMBER(1), FILENAME VARCHAR2(255), MIME VARCHAR2(255) NOT NULL, USER_MESSAGE_ID_FK NUMBER(38, 0) NOT NULL, PART_ORDER INTEGER DEFAULT 0 NOT NULL, ENCRYPTED NUMBER(1) DEFAULT 0, COMPRESSED NUMBER(1) DEFAULT 0, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), PART_LENGTH NUMBER(38, 0) DEFAULT -1 NOT NULL, CONSTRAINT PK_PART_INFO PRIMARY KEY (ID_PK));

ALTER TABLE TB_PART_INFO ADD CONSTRAINT FK_PART_INFO_USER_MSG FOREIGN KEY (USER_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK) ON DELETE CASCADE;

CREATE INDEX FK_USER_MESSAGE_ID ON TB_PART_INFO(USER_MESSAGE_ID_FK);

CREATE TABLE TB_PART_PROPERTIES (PART_INFO_ID_FK NUMBER(38, 0) NOT NULL, PART_INFO_PROPERTY_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PART_PROPERTIES ADD CONSTRAINT PK_PART_PROPERTIES PRIMARY KEY (PART_INFO_ID_FK, PART_INFO_PROPERTY_FK);

ALTER TABLE TB_PART_PROPERTIES ADD CONSTRAINT FK_PART_PROPS_PART_INFO FOREIGN KEY (PART_INFO_ID_FK) REFERENCES TB_PART_INFO (ID_PK) ON DELETE CASCADE;

ALTER TABLE TB_PART_PROPERTIES ADD CONSTRAINT FK_PART_PROPS_PART_PROP FOREIGN KEY (PART_INFO_PROPERTY_FK) REFERENCES TB_D_PART_PROPERTY (ID_PK);

CREATE INDEX IDX_PART_PROPS_PART_PROP ON TB_PART_PROPERTIES(PART_INFO_PROPERTY_FK);

CREATE TABLE TB_MESSAGE_PROPERTIES (USER_MESSAGE_ID_FK NUMBER(38, 0) NOT NULL, MESSAGE_PROPERTY_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_MESSAGE_PROPERTIES ADD CONSTRAINT PK_MESSAGE_PROPERTIES PRIMARY KEY (USER_MESSAGE_ID_FK, MESSAGE_PROPERTY_FK);

ALTER TABLE TB_MESSAGE_PROPERTIES ADD CONSTRAINT FK_MSG_PROPS_USER_MSG FOREIGN KEY (USER_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK);

ALTER TABLE TB_MESSAGE_PROPERTIES ADD CONSTRAINT FK_MSG_PROPS_MSG_PROP FOREIGN KEY (MESSAGE_PROPERTY_FK) REFERENCES TB_D_MESSAGE_PROPERTY (ID_PK);

CREATE TABLE TB_USER_MESSAGE_RAW (ID_PK NUMBER(38, 0) NOT NULL, RAW_XML BLOB, COMPRESSED NUMBER(1) DEFAULT 0, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_USER_MESSAGE_RAW PRIMARY KEY (ID_PK));

ALTER TABLE TB_USER_MESSAGE_RAW ADD CONSTRAINT FK_MSG_RAW_USER_MSG FOREIGN KEY (ID_PK) REFERENCES TB_USER_MESSAGE (ID_PK);

CREATE TABLE TB_SIGNAL_MESSAGE (ID_PK NUMBER(38, 0) NOT NULL, SIGNAL_MESSAGE_ID VARCHAR2(255), MSH_ROLE_ID_FK NUMBER(38, 0) NOT NULL, REF_TO_MESSAGE_ID VARCHAR2(255), EBMS3_TIMESTAMP TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SIGNAL_MESSAGE PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_SIGNAL_MESSAGE.EBMS3_TIMESTAMP IS 'the EBMS3 timestamp present in eb:Messaging/eb:UserMessage/eb:MessageInfo/eb:Timestamp';

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT FK_TB_SIGNAL_USER_MSG FOREIGN KEY (ID_PK) REFERENCES TB_USER_MESSAGE (ID_PK);

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT FK_SIGNAL_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

CREATE INDEX IDX_SIG_MESS_REF_TO_MESS_ID ON TB_SIGNAL_MESSAGE(REF_TO_MESSAGE_ID);

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT UK_SIGNAL_MSG_MESSAGE_ID UNIQUE (SIGNAL_MESSAGE_ID, MSH_ROLE_ID_FK);

CREATE TABLE TB_SIGNAL_MESSAGE_LOG (ID_PK NUMBER(38, 0) NOT NULL, RECEIVED TIMESTAMP NOT NULL, DELETED TIMESTAMP, MESSAGE_STATUS_ID_FK NUMBER(38, 0), MSH_ROLE_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SIGNAL_MESSAGE_LOG PRIMARY KEY (ID_PK));

ALTER TABLE TB_SIGNAL_MESSAGE_LOG ADD CONSTRAINT FK_SIGNAL_LOG_SIGNAL_ID FOREIGN KEY (ID_PK) REFERENCES TB_SIGNAL_MESSAGE (ID_PK);

ALTER TABLE TB_SIGNAL_MESSAGE_LOG ADD CONSTRAINT FK_SIGNAL_LOG_MSG_STATUS FOREIGN KEY (MESSAGE_STATUS_ID_FK) REFERENCES TB_D_MESSAGE_STATUS (ID_PK);

ALTER TABLE TB_SIGNAL_MESSAGE_LOG ADD CONSTRAINT FK_SIGNAL_LOG_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

CREATE INDEX IDX_SIGNAL_LOG_MSG_STATUS_ID ON TB_SIGNAL_MESSAGE_LOG(MESSAGE_STATUS_ID_FK);

CREATE INDEX IDX_SIGNAL_LOG_MSG_ROLE_ID ON TB_SIGNAL_MESSAGE_LOG(MSH_ROLE_ID_FK);

CREATE INDEX IDX_SIGNAL_LOG_RECEIVED ON TB_SIGNAL_MESSAGE_LOG(RECEIVED);

CREATE TABLE TB_RECEIPT (ID_PK NUMBER(38, 0) NOT NULL, RAW_XML BLOB, COMPRESSED NUMBER(1) DEFAULT 0, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_RECEIPT PRIMARY KEY (ID_PK));

ALTER TABLE TB_RECEIPT ADD CONSTRAINT FK_TB_RECEIPT_SIGNAL_MSG FOREIGN KEY (ID_PK) REFERENCES TB_SIGNAL_MESSAGE (ID_PK);

CREATE TABLE TB_SIGNAL_MESSAGE_RAW (ID_PK NUMBER(38, 0) NOT NULL, RAW_XML BLOB, COMPRESSED NUMBER(1) DEFAULT 0, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SIGNAL_MESSAGE_RAW PRIMARY KEY (ID_PK));

ALTER TABLE TB_SIGNAL_MESSAGE_RAW ADD CONSTRAINT FK_SIGNAL_MSG_RAW_SIGNAL_MSG FOREIGN KEY (ID_PK) REFERENCES TB_SIGNAL_MESSAGE (ID_PK);

CREATE TABLE TB_SEND_ATTEMPT (ID_PK NUMBER(38, 0) NOT NULL, START_DATE TIMESTAMP NOT NULL, END_DATE TIMESTAMP NOT NULL, STATUS VARCHAR2(255) NOT NULL, ERROR VARCHAR2(255), USER_MESSAGE_ID_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_SEND_ATTEMPT PRIMARY KEY (ID_PK));

ALTER TABLE TB_SEND_ATTEMPT ADD CONSTRAINT FK_SEND_ATTEMPT_USER_MSG FOREIGN KEY (USER_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK);

CREATE INDEX IDX_MESSAGE_ID_FK ON TB_SEND_ATTEMPT(USER_MESSAGE_ID_FK);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-10924::idragusa
DROP INDEX IDX_USER_LOG_RECEIVED;

CREATE INDEX IDX_USER_LOG_RECEIVED ON TB_USER_MESSAGE_LOG(RECEIVED) REVERSE;

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-Miscellaneous Tables::Cosmin Baciu
CREATE TABLE TB_CERTIFICATE (ID_PK NUMBER(38, 0) NOT NULL, CERTIFICATE_ALIAS VARCHAR2(255) NOT NULL, NOT_VALID_BEFORE_DATE TIMESTAMP, NOT_VALID_AFTER_DATE TIMESTAMP, REVOKE_NOTIFICATION_DATE TIMESTAMP, ALERT_IMM_NOTIFICATION_DATE TIMESTAMP, ALERT_EXP_NOTIFICATION_DATE TIMESTAMP, CERTIFICATE_STATUS VARCHAR2(255) NOT NULL, CERTIFICATE_TYPE VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_CERTIFICATE PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_CERTIFICATE.ALERT_IMM_NOTIFICATION_DATE IS 'Alert imminent notification date';

COMMENT ON COLUMN TB_CERTIFICATE.ALERT_EXP_NOTIFICATION_DATE IS 'Alert expired notification date';

ALTER TABLE TB_CERTIFICATE ADD CONSTRAINT UK_CERTIFICATE_ALIAS UNIQUE (CERTIFICATE_ALIAS, CERTIFICATE_TYPE);

CREATE TABLE TB_REV_INFO (ID NUMBER(38, 0) NOT NULL, TIMESTAMP NUMBER(38, 0), REVISION_DATE TIMESTAMP, USER_NAME VARCHAR2(255), CONSTRAINT PK_REV_INFO PRIMARY KEY (ID));

CREATE TABLE TB_REV_CHANGES (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0), AUDIT_ORDER INTEGER, ENTITY_NAME VARCHAR2(255), GROUP_NAME VARCHAR2(255), ENTITY_ID VARCHAR2(255), MODIFICATION_TYPE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_REV_CHANGES PRIMARY KEY (ID_PK));

ALTER TABLE TB_REV_CHANGES ADD CONSTRAINT FK_REV_CHANGES_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_REV_CHANGES_REV_INFO ON TB_REV_CHANGES(REV);

CREATE TABLE TB_CERTIFICATE_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), CERTIFICATE_ALIAS VARCHAR2(255), NOT_VALID_BEFORE_DATE TIMESTAMP, NOT_VALID_AFTER_DATE TIMESTAMP, REVOKE_NOTIFICATION_DATE TIMESTAMP, ALERT_IMM_NOTIFICATION_DATE TIMESTAMP, ALERT_EXP_NOTIFICATION_DATE TIMESTAMP, CERTIFICATE_STATUS VARCHAR2(255), CERTIFICATE_TYPE VARCHAR2(255), CONSTRAINT PK_CERTIFICATE_AUD PRIMARY KEY (ID_PK, REV));

COMMENT ON COLUMN TB_CERTIFICATE_AUD.ALERT_IMM_NOTIFICATION_DATE IS 'Alert imminent notification date';

COMMENT ON COLUMN TB_CERTIFICATE_AUD.ALERT_EXP_NOTIFICATION_DATE IS 'Alert expired notification date';

ALTER TABLE TB_CERTIFICATE_AUD ADD CONSTRAINT FK_CERTIFICATE_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_CERTIFICATE_AUD_REV ON TB_CERTIFICATE_AUD(REV);

CREATE TABLE TB_COMMAND (ID_PK NUMBER(38, 0) NOT NULL, SERVER_NAME VARCHAR2(255) NOT NULL, COMMAND_NAME VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_COMMAND PRIMARY KEY (ID_PK));

COMMENT ON TABLE TB_COMMAND IS 'Stores commands to be executed by different nodes in clustered environments';

COMMENT ON COLUMN TB_COMMAND.SERVER_NAME IS 'The target server name';

CREATE TABLE TB_COMMAND_PROPERTY (PROPERTY_NAME VARCHAR2(50) NOT NULL, PROPERTY_VALUE VARCHAR2(2048), FK_COMMAND NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

COMMENT ON TABLE TB_COMMAND_PROPERTY IS 'Stores properties/parameters of the commands to be executed by different nodes in clustered environments';

COMMENT ON COLUMN TB_COMMAND_PROPERTY.FK_COMMAND IS 'Reference to the parent command';

ALTER TABLE TB_COMMAND_PROPERTY ADD CONSTRAINT FK_COMMAND_PROPERTY_ID FOREIGN KEY (FK_COMMAND) REFERENCES TB_COMMAND (ID_PK);

ALTER TABLE TB_COMMAND_PROPERTY ADD CONSTRAINT UK_COMMAND_PROP_NAME UNIQUE (FK_COMMAND, PROPERTY_NAME);

CREATE TABLE TB_ENCRYPTION_KEY (ID_PK NUMBER(38, 0) NOT NULL, KEY_USAGE VARCHAR2(255), SECRET_KEY BLOB NOT NULL, INIT_VECTOR BLOB NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_ENCRYPTION_KEY PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_ENCRYPTION_KEY.KEY_USAGE IS 'The encryption usage: PAYLOAD';

COMMENT ON COLUMN TB_ENCRYPTION_KEY.SECRET_KEY IS 'The secret key used for symmetric encryption';

COMMENT ON COLUMN TB_ENCRYPTION_KEY.INIT_VECTOR IS 'The initialization vector used for encryption';

ALTER TABLE TB_ENCRYPTION_KEY ADD CONSTRAINT UK_KEY_USAGE UNIQUE (KEY_USAGE);

CREATE TABLE TB_ERROR_LOG (ID_PK NUMBER(38, 0) NOT NULL, ERROR_CODE VARCHAR2(255), ERROR_DETAIL VARCHAR2(255), ERROR_SIGNAL_MESSAGE_ID VARCHAR2(255), MESSAGE_IN_ERROR_ID VARCHAR2(255), MSH_ROLE_ID_FK NUMBER(38, 0), NOTIFIED TIMESTAMP, TIME_STAMP TIMESTAMP, USER_MESSAGE_ID_FK NUMBER(38, 0) DEFAULT 19700101 NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_ERROR_LOG PRIMARY KEY (ID_PK));

ALTER TABLE TB_ERROR_LOG ADD CONSTRAINT FK_ERROR_LOG_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK);

ALTER TABLE TB_ERROR_LOG ADD CONSTRAINT FK_ERROR_LOG_MSG_ID FOREIGN KEY (USER_MESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK);

CREATE INDEX IDX_ERROR_LOG_MSH_ROLE_ID ON TB_ERROR_LOG(MSH_ROLE_ID_FK);

CREATE INDEX IDX_ERROR_LOG_MSG_ID ON TB_ERROR_LOG(USER_MESSAGE_ID_FK);

CREATE INDEX IDX_MESSAGE_IN_ERROR_ID ON TB_ERROR_LOG(MESSAGE_IN_ERROR_ID);

CREATE INDEX IDX_SIGNAL_MESSAGE_ID ON TB_ERROR_LOG(ERROR_SIGNAL_MESSAGE_ID);

CREATE TABLE TB_VERSION (VERSION VARCHAR2(30), BUILD_TIME VARCHAR2(30), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL);

COMMENT ON TABLE TB_VERSION IS 'Stores Domibus version and build time';

ALTER TABLE TB_VERSION ADD CONSTRAINT UK_VERSION UNIQUE (VERSION);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-PMode Tables::Cosmin Baciu
CREATE TABLE TB_PM_BUSINESS_PROCESS (ID_PK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_BUSINESS_PROCESS PRIMARY KEY (ID_PK));

CREATE TABLE TB_PM_ACTION (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), VALUE VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_ACTION PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_ACTION ADD CONSTRAINT FK_ACTION_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_ACTION_BP ON TB_PM_ACTION(FK_BUSINESSPROCESS);

CREATE TABLE TB_ACTION_AUDIT (ID_PK NUMBER(38, 0) NOT NULL, AUDIT_TYPE VARCHAR2(31) NOT NULL, ENTITY_ID VARCHAR2(255), MODIFICATION_TYPE VARCHAR2(255), REVISION_DATE TIMESTAMP, USER_NAME VARCHAR2(255), FROM_QUEUE VARCHAR2(255), TO_QUEUE VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_ACTION_AUDIT PRIMARY KEY (ID_PK));

CREATE OR REPLACE VIEW V_AUDIT_DETAIL AS SELECT
                DISTINCT rc.GROUP_NAME as AUDIT_TYPE ,
                         rc.MODIFICATION_TYPE as ACTION_TYPE,
                         ri.USER_NAME as USER_NAME ,
                         ri.REVISION_DATE as AUDIT_DATE,
                         COALESCE(TRIM(CAST(rc.ENTITY_ID AS CHAR(255))), '') AS ID,
                         COALESCE(TRIM(CAST(ri.ID AS CHAR(19))), '') AS REV_ID
            FROM TB_REV_INFO ri, TB_REV_CHANGES rc
            WHERE ri.ID=rc.REV
            UNION
            SELECT aa.AUDIT_TYPE,aa.MODIFICATION_TYPE,aa.USER_NAME,aa.REVISION_DATE,aa.ENTITY_ID,'1' FROM
                TB_ACTION_AUDIT aa;

CREATE OR REPLACE VIEW V_AUDIT AS SELECT *
            FROM V_AUDIT_DETAIL VAD
            ORDER BY VAD.AUDIT_DATE DESC;

CREATE TABLE TB_PM_AGREEMENT (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), TYPE VARCHAR2(255), VALUE VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_AGREEMENT PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_AGREEMENT ADD CONSTRAINT FK_AGREEMENT_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_AGREEMENT_BP ON TB_PM_AGREEMENT(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_PARTY (ID_PK NUMBER(38, 0) NOT NULL, ENDPOINT VARCHAR2(1024), NAME VARCHAR2(255), "PASSWORD" VARCHAR2(255), USERNAME VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PARTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_PARTY ADD CONSTRAINT FK_PARTY_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_PARTY_BP ON TB_PM_PARTY(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_CONFIGURATION (ID_PK NUMBER(38, 0) NOT NULL, FK_BUSINESSPROCESSES NUMBER(38, 0), FK_PARTY NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_CONFIGURATION PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_CONFIGURATION ADD CONSTRAINT FK_CONFIG_PARTY FOREIGN KEY (FK_PARTY) REFERENCES TB_PM_PARTY (ID_PK);

ALTER TABLE TB_PM_CONFIGURATION ADD CONSTRAINT FK_CONFIG_BP FOREIGN KEY (FK_BUSINESSPROCESSES) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_CONFIG_PARTY ON TB_PM_CONFIGURATION(FK_PARTY);

CREATE INDEX IDX_FK_CONFIG_BP ON TB_PM_CONFIGURATION(FK_BUSINESSPROCESSES);

CREATE TABLE TB_PM_CONFIGURATION_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), EXPRESSION VARCHAR2(255), EXPRESSION_MOD NUMBER(1), NAME VARCHAR2(255), NAME_MOD NUMBER(1), CONSTRAINT PK_CONFIGURATION_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_PM_CONFIGURATION_AUD ADD CONSTRAINT FK_CONFIG_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_CONFIG_AUD_REV ON TB_PM_CONFIGURATION_AUD(REV);

CREATE TABLE TB_PM_CONFIGURATION_RAW (ID_PK NUMBER(38, 0) NOT NULL, CONFIGURATION_DATE TIMESTAMP, XML BLOB, DESCRIPTION VARCHAR2(255) DEFAULT '', CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_CONFIGURATION_RAW PRIMARY KEY (ID_PK));

CREATE TABLE TB_PM_CONFIGURATION_RAW_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), CONFIGURATION_DATE TIMESTAMP, CONFIGURATIONDATE_MOD NUMBER(1), DESCRIPTION VARCHAR2(255), DESCRIPTION_MOD VARCHAR2(255), XML BLOB, XML_MOD NUMBER(1), CONSTRAINT PK_CONFIGURATION_RAW_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_PM_CONFIGURATION_RAW_AUD ADD CONSTRAINT FK_CONFIG_RAW_AUD FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_CONFIG_RAW_AUD ON TB_PM_CONFIGURATION_RAW_AUD(REV);

CREATE TABLE TB_PM_ERROR_HANDLING (ID_PK NUMBER(38, 0) NOT NULL, BUSINESS_ERROR_NOTIFY_CONSUMER NUMBER(1), BUSINESS_ERROR_NOTIFY_PRODUCER NUMBER(1), DELIVERY_FAIL_NOTIFY_PRODUCER NUMBER(1), ERROR_AS_RESPONSE NUMBER(1), NAME VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_ERROR_HANDLING PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_ERROR_HANDLING ADD CONSTRAINT FK_ERROR_HANDLING_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_ERROR_HANDLING_BP ON TB_PM_ERROR_HANDLING(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_PAYLOAD_PROFILE (ID_PK NUMBER(38, 0) NOT NULL, MAX_SIZE NUMBER(38, 0), NAME VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PAYLOAD_PROFILE PRIMARY KEY (ID_PK));

CREATE TABLE TB_PM_PAYLOAD (ID_PK NUMBER(38, 0) NOT NULL, CID VARCHAR2(255), IN_BODY NUMBER(1), MAX_SIZE INTEGER, MIME_TYPE VARCHAR2(255), NAME VARCHAR2(255), REQUIRED_ NUMBER(1), SCHEMA_FILE VARCHAR2(1024), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PAYLOAD PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_PAYLOAD ADD CONSTRAINT FK_PAYLOAD_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_PAYLOAD_BP ON TB_PM_PAYLOAD(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_JOIN_PAYLOAD_PROFILE (FK_PAYLOAD NUMBER(38, 0) NOT NULL, FK_PROFILE NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PM_JOIN_PAYLOAD_PROFILE ADD CONSTRAINT FK_JP_PROFILE FOREIGN KEY (FK_PAYLOAD) REFERENCES TB_PM_PAYLOAD_PROFILE (ID_PK);

ALTER TABLE TB_PM_JOIN_PAYLOAD_PROFILE ADD CONSTRAINT FK_JP_PAYLOAD FOREIGN KEY (FK_PROFILE) REFERENCES TB_PM_PAYLOAD (ID_PK);

CREATE INDEX IDX_FK_JP_PROFILE ON TB_PM_JOIN_PAYLOAD_PROFILE(FK_PAYLOAD);

CREATE INDEX IDX_FK_JP_PAYLOAD ON TB_PM_JOIN_PAYLOAD_PROFILE(FK_PROFILE);

CREATE TABLE TB_PM_MEP_BINDING (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), VALUE VARCHAR2(1024), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_MEP_BINDING PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_MEP_BINDING ADD CONSTRAINT FK_MEP_BINDING_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_MEP_BINDING_BP ON TB_PM_MEP_BINDING(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_ROLE (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), VALUE VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_ROLE PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_ROLE ADD CONSTRAINT FK_ROLE_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_ROLE_BP ON TB_PM_ROLE(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_MEP (ID_PK NUMBER(38, 0) NOT NULL, LEG_COUNT INTEGER, NAME VARCHAR2(255), VALUE VARCHAR2(1024), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_MEP PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_MEP ADD CONSTRAINT FK_MEP_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_MEP_BP ON TB_PM_MEP(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_PROCESS (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), FK_AGREEMENT NUMBER(38, 0), FK_INITIATOR_ROLE NUMBER(38, 0), FK_MEP NUMBER(38, 0), FK_MEP_BINDING NUMBER(38, 0), FK_RESPONDER_ROLE NUMBER(38, 0), FK_BUSINESSPROCESS NUMBER(38, 0), USE_DYNAMIC_INITIATOR NUMBER(1) NOT NULL, USE_DYNAMIC_RESPONDER NUMBER(1) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PROCESS PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_MEP_BINDING FOREIGN KEY (FK_MEP_BINDING) REFERENCES TB_PM_MEP_BINDING (ID_PK);

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_INITIATOR_ROLE FOREIGN KEY (FK_INITIATOR_ROLE) REFERENCES TB_PM_ROLE (ID_PK);

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_MEP FOREIGN KEY (FK_MEP) REFERENCES TB_PM_MEP (ID_PK);

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_RESPONDER_ROLE FOREIGN KEY (FK_RESPONDER_ROLE) REFERENCES TB_PM_ROLE (ID_PK);

ALTER TABLE TB_PM_PROCESS ADD CONSTRAINT FK_PROCESS_AGREEMENT FOREIGN KEY (FK_AGREEMENT) REFERENCES TB_PM_AGREEMENT (ID_PK);

CREATE INDEX IDX_FK_PROCESS_MEP_BINDING ON TB_PM_PROCESS(FK_MEP_BINDING);

CREATE INDEX IDX_FK_PROCESS_INIT_ROLE ON TB_PM_PROCESS(FK_INITIATOR_ROLE);

CREATE INDEX IDX_FK_PROCESS_AGRMNT ON TB_PM_PROCESS(FK_AGREEMENT);

CREATE INDEX IDX_FK_PROCESS_MEP ON TB_PM_PROCESS(FK_MEP);

CREATE INDEX IDX_FK_PROCESS_BP ON TB_PM_PROCESS(FK_BUSINESSPROCESS);

CREATE INDEX IDX_FK_PROCESS_RESP_ROLE ON TB_PM_PROCESS(FK_RESPONDER_ROLE);

CREATE TABLE TB_PM_JOIN_PROCESS_INIT_PARTY (PROCESS_FK NUMBER(38, 0) NOT NULL, PARTY_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PM_JOIN_PROCESS_INIT_PARTY ADD CONSTRAINT FK_JOIN_INIT_PARTY_PRS FOREIGN KEY (PROCESS_FK) REFERENCES TB_PM_PROCESS (ID_PK);

ALTER TABLE TB_PM_JOIN_PROCESS_INIT_PARTY ADD CONSTRAINT FK_JOIN_INIT_PARTY FOREIGN KEY (PARTY_FK) REFERENCES TB_PM_PARTY (ID_PK);

CREATE INDEX IDX_FK_JOIN_INIT_PARTY_PRS ON TB_PM_JOIN_PROCESS_INIT_PARTY(PROCESS_FK);

CREATE INDEX IDX_FK_JOIN_INIT_PARTY ON TB_PM_JOIN_PROCESS_INIT_PARTY(PARTY_FK);

CREATE TABLE TB_PM_SECURITY (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), POLICY VARCHAR2(255), SIGNATURE_METHOD VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_SECURITY PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_SECURITY ADD CONSTRAINT FK_SECURITY_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_SECURITY_BP ON TB_PM_SECURITY(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_SERVICE (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), SERVICE_TYPE VARCHAR2(255), VALUE VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_SERVICE PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_SERVICE ADD CONSTRAINT FK_SERVICE_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_SERVICE_BP ON TB_PM_SERVICE(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_RECEPTION_AWARENESS (ID_PK NUMBER(38, 0) NOT NULL, DUPLICATE_DETECTION NUMBER(1), NAME VARCHAR2(255), RETRY_COUNT INTEGER, RETRY_TIMEOUT INTEGER, INITIAL_INTERVAL INTEGER DEFAULT 0, MULTIPLYING_FACTOR INTEGER DEFAULT 0, STRATEGY VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_RECEPTION_AWARENESS PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_RECEPTION_AWARENESS ADD CONSTRAINT FK_REC_AWRNS_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_REC_AWRNS_BP ON TB_PM_RECEPTION_AWARENESS(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_RELIABILITY (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), NON_REPUDIATION NUMBER(1), REPLY_PATTERN VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_RELIABILITY PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_RELIABILITY ADD CONSTRAINT FK_RELIABILITY_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_RELIABILITY_BP ON TB_PM_RELIABILITY(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_MPC (ID_PK NUMBER(38, 0) NOT NULL, DEFAULT_MPC NUMBER(1), IS_ENABLED NUMBER(1), NAME VARCHAR2(255), QUALIFIED_NAME VARCHAR2(255), RETENTION_DOWNLOADED INTEGER, RETENTION_UNDOWNLOADED INTEGER, RETENTION_SENT INTEGER DEFAULT -1, DELETE_MESSAGE_METADATA NUMBER(1) DEFAULT 0, RETENTION_METADATA_OFFSET INTEGER DEFAULT 0, MAX_BATCH_DELETE INTEGER DEFAULT -1, FK_CONFIGURATION NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_MPC PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_PM_MPC.RETENTION_SENT IS 'Retention time for sent messages (both send success and send failure)';

COMMENT ON COLUMN TB_PM_MPC.DELETE_MESSAGE_METADATA IS 'Specifies whether the message metadata should be deleted or not.';

COMMENT ON COLUMN TB_PM_MPC.MAX_BATCH_DELETE IS 'Maximum number of DOWNLOADED/UNDOWNLOADED/SENT messages to be deleted in one batch';

ALTER TABLE TB_PM_MPC ADD CONSTRAINT FK_MPC_CONFIGURATION FOREIGN KEY (FK_CONFIGURATION) REFERENCES TB_PM_CONFIGURATION (ID_PK);

CREATE INDEX IDX_FK_MPC_CONFIGURATION ON TB_PM_MPC(FK_CONFIGURATION);

CREATE TABLE TB_PM_MESSAGE_PROPERTY_SET (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_MESSAGE_PROPERTY_SET PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_MESSAGE_PROPERTY_SET ADD CONSTRAINT FK_PROPERTY_SET_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_PROPERTY_SET_BP ON TB_PM_MESSAGE_PROPERTY_SET(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_SPLITTING (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), FRAGMENT_SIZE INTEGER, COMPRESSION NUMBER(1), COMPRESSION_ALGORITHM VARCHAR2(255), JOIN_INTERVAL INTEGER, FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_SPLITTING PRIMARY KEY (ID_PK));

COMMENT ON TABLE TB_PM_SPLITTING IS 'Stores the configuration of the SplitAndJoin parameters configured in the PMode';

COMMENT ON COLUMN TB_PM_SPLITTING.NAME IS 'Splitting configuration name';

COMMENT ON COLUMN TB_PM_SPLITTING.FRAGMENT_SIZE IS 'The fragment size';

COMMENT ON COLUMN TB_PM_SPLITTING.COMPRESSION IS 'True if compression will be used';

COMMENT ON COLUMN TB_PM_SPLITTING.COMPRESSION_ALGORITHM IS 'Compression algorithm to use for compressing the SourceMessage';

COMMENT ON COLUMN TB_PM_SPLITTING.JOIN_INTERVAL IS 'The join interval';

COMMENT ON COLUMN TB_PM_SPLITTING.FK_BUSINESSPROCESS IS 'Foreign key to the business process';

CREATE INDEX IDX_FK_SPLT_BP ON TB_PM_SPLITTING(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_LEG (ID_PK NUMBER(38, 0) NOT NULL, COMPRESS_PAYLOADS NUMBER(1), NAME VARCHAR2(255), FK_ACTION NUMBER(38, 0), FK_MPC NUMBER(38, 0), FK_ERROR_HANDLING NUMBER(38, 0), FK_PAYLOAD_PROFILE NUMBER(38, 0), FK_PROPERTY_SET NUMBER(38, 0), FK_RECEPTION_AWARENESS NUMBER(38, 0), FK_RELIABILITY NUMBER(38, 0), FK_SECURITY NUMBER(38, 0), FK_SERVICE NUMBER(38, 0), FK_BUSINESSPROCESS NUMBER(38, 0), FK_SPLITTING NUMBER(38, 0), ASYNC_NOTIFICATION NUMBER(1), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_LEG PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_SPLT FOREIGN KEY (FK_SPLITTING) REFERENCES TB_PM_SPLITTING (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_PROPERTY_SET FOREIGN KEY (FK_PROPERTY_SET) REFERENCES TB_PM_MESSAGE_PROPERTY_SET (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_ERROR_HANDLING FOREIGN KEY (FK_ERROR_HANDLING) REFERENCES TB_PM_ERROR_HANDLING (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_ACTION FOREIGN KEY (FK_ACTION) REFERENCES TB_PM_ACTION (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_PAYLOAD_PROFILE FOREIGN KEY (FK_PAYLOAD_PROFILE) REFERENCES TB_PM_PAYLOAD_PROFILE (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_SECURITY FOREIGN KEY (FK_SECURITY) REFERENCES TB_PM_SECURITY (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_SERVICE FOREIGN KEY (FK_SERVICE) REFERENCES TB_PM_SERVICE (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_REC_AWRNS FOREIGN KEY (FK_RECEPTION_AWARENESS) REFERENCES TB_PM_RECEPTION_AWARENESS (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_MPC FOREIGN KEY (FK_MPC) REFERENCES TB_PM_MPC (ID_PK);

ALTER TABLE TB_PM_LEG ADD CONSTRAINT FK_LEG_RELIABILITY FOREIGN KEY (FK_RELIABILITY) REFERENCES TB_PM_RELIABILITY (ID_PK);

CREATE INDEX IDX_FK_LEG_REC_AWRNS ON TB_PM_LEG(FK_RECEPTION_AWARENESS);

CREATE INDEX IDX_FK_LEG_BP ON TB_PM_LEG(FK_BUSINESSPROCESS);

CREATE INDEX IDX_FK_LEG_MPC ON TB_PM_LEG(FK_MPC);

CREATE INDEX IDX_FK_LEG_SPLT ON TB_PM_LEG(FK_SPLITTING);

CREATE INDEX IDX_FK_LEG_PROPERTY_SET ON TB_PM_LEG(FK_PROPERTY_SET);

CREATE INDEX IDX_FK_LEG_SERVICE ON TB_PM_LEG(FK_SERVICE);

CREATE INDEX IDX_FK_LEG_ERROR_HANDLING ON TB_PM_LEG(FK_ERROR_HANDLING);

CREATE INDEX IDX_FK_LEG_ACTION ON TB_PM_LEG(FK_ACTION);

CREATE INDEX IDX_FK_LEG_PAYLOAD_PROFILE ON TB_PM_LEG(FK_PAYLOAD_PROFILE);

CREATE INDEX IDX_FK_LEG_SECURITY ON TB_PM_LEG(FK_SECURITY);

CREATE INDEX IDX_FK_LEG_RELIABILITY ON TB_PM_LEG(FK_RELIABILITY);

CREATE TABLE TB_PM_JOIN_PROCESS_LEG (PROCESS_FK NUMBER(38, 0) NOT NULL, LEG_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PM_JOIN_PROCESS_LEG ADD CONSTRAINT FK_JOIN_PROCESS_LEG FOREIGN KEY (LEG_FK) REFERENCES TB_PM_LEG (ID_PK);

ALTER TABLE TB_PM_JOIN_PROCESS_LEG ADD CONSTRAINT FK_JOIN_PROC_LEG_PROC FOREIGN KEY (PROCESS_FK) REFERENCES TB_PM_PROCESS (ID_PK);

CREATE INDEX IDX_FK_JOIN_PROCESS_LEG ON TB_PM_JOIN_PROCESS_LEG(LEG_FK);

CREATE INDEX IDX_FK_JOIN_PROC_LEG_PROC ON TB_PM_JOIN_PROCESS_LEG(PROCESS_FK);

CREATE TABLE TB_PM_JOIN_PROCESS_RESP_PARTY (PROCESS_FK NUMBER(38, 0) NOT NULL, PARTY_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PM_JOIN_PROCESS_RESP_PARTY ADD CONSTRAINT FK_JOIN_PROC_RESP_PARTY FOREIGN KEY (PARTY_FK) REFERENCES TB_PM_PARTY (ID_PK);

ALTER TABLE TB_PM_JOIN_PROCESS_RESP_PARTY ADD CONSTRAINT FK_JN_PROC_RESP_PRT_PROC FOREIGN KEY (PROCESS_FK) REFERENCES TB_PM_PROCESS (ID_PK);

CREATE INDEX IDX_FK_JOIN_PROC_RESP_PARTY ON TB_PM_JOIN_PROCESS_RESP_PARTY(PARTY_FK);

CREATE INDEX IDX_FK_JN_PROC_RESP_PRT_PROC ON TB_PM_JOIN_PROCESS_RESP_PARTY(PROCESS_FK);

CREATE TABLE TB_PM_MESSAGE_PROPERTY (ID_PK NUMBER(38, 0) NOT NULL, DATATYPE VARCHAR2(255), KEY_ VARCHAR2(255), NAME VARCHAR2(255), REQUIRED_ NUMBER(1), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_MESSAGE_PROPERTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_MESSAGE_PROPERTY ADD CONSTRAINT FK_MESSAGE_PROPERTY_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_MESSAGE_PROPERTY_BP ON TB_PM_MESSAGE_PROPERTY(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_JOIN_PROPERTY_SET (PROPERTY_FK NUMBER(38, 0) NOT NULL, SET_FK NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

ALTER TABLE TB_PM_JOIN_PROPERTY_SET ADD CONSTRAINT FK_JOIN_PROP_SET_PROP FOREIGN KEY (PROPERTY_FK) REFERENCES TB_PM_MESSAGE_PROPERTY_SET (ID_PK);

ALTER TABLE TB_PM_JOIN_PROPERTY_SET ADD CONSTRAINT FK_JOIN_PROPERTY_SET FOREIGN KEY (SET_FK) REFERENCES TB_PM_MESSAGE_PROPERTY (ID_PK);

CREATE INDEX IDX_FK_JOIN_PROP_SET_PROP ON TB_PM_JOIN_PROPERTY_SET(PROPERTY_FK);

CREATE INDEX IDX_FK_JOIN_PROPERTY_SET ON TB_PM_JOIN_PROPERTY_SET(SET_FK);

CREATE TABLE TB_PM_LEG_MPC (LEGCONFIGURATION_ID_PK NUMBER(38, 0) NOT NULL, PARTYMPCMAP_ID_PK NUMBER(38, 0) NOT NULL, PARTYMPCMAP_KEY NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PRIMARY_12 PRIMARY KEY (LEGCONFIGURATION_ID_PK, PARTYMPCMAP_KEY));

ALTER TABLE TB_PM_LEG_MPC ADD CONSTRAINT FK_LEG_MPC_LEG FOREIGN KEY (LEGCONFIGURATION_ID_PK) REFERENCES TB_PM_LEG (ID_PK);

ALTER TABLE TB_PM_LEG_MPC ADD CONSTRAINT FK_LEG_MPC_PARTY FOREIGN KEY (PARTYMPCMAP_KEY) REFERENCES TB_PM_PARTY (ID_PK);

ALTER TABLE TB_PM_LEG_MPC ADD CONSTRAINT UK_LEG_MPC_PARTYMPCMAP_ID UNIQUE (PARTYMPCMAP_ID_PK);

ALTER TABLE TB_PM_LEG_MPC ADD CONSTRAINT FK_LEG_MPC_MPC FOREIGN KEY (PARTYMPCMAP_ID_PK) REFERENCES TB_PM_MPC (ID_PK);

CREATE INDEX IDX_FK_LEG_MPC_PARTY ON TB_PM_LEG_MPC(PARTYMPCMAP_KEY);

CREATE TABLE TB_PM_PARTY_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), ENDPOINT VARCHAR2(1024), ENDPOINT_MOD NUMBER(1), NAME VARCHAR2(255), NAME_MOD NUMBER(1), "PASSWORD" VARCHAR2(255), PASSWORD_MOD NUMBER(1), USERNAME VARCHAR2(255), USERNAME_MOD NUMBER(1), CONSTRAINT PK_PARTY_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_PM_PARTY_AUD ADD CONSTRAINT FK_PARTY_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_PARTY_AUD_REV ON TB_PM_PARTY_AUD(REV);

CREATE TABLE TB_PM_PARTY_ID_TYPE (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(255), VALUE VARCHAR2(1024), FK_BUSINESSPROCESS NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PARTY_ID_TYPE PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_PARTY_ID_TYPE ADD CONSTRAINT FK_PARTY_ID_TYPE_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_PARTY_ID_TYPE_BP ON TB_PM_PARTY_ID_TYPE(FK_BUSINESSPROCESS);

CREATE TABLE TB_PM_PARTY_IDENTIFIER (ID_PK NUMBER(38, 0) NOT NULL, PARTY_ID VARCHAR2(255), FK_PARTY_ID_TYPE NUMBER(38, 0), FK_PARTY NUMBER(38, 0), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PM_PARTY_IDENTIFIER PRIMARY KEY (ID_PK));

ALTER TABLE TB_PM_PARTY_IDENTIFIER ADD CONSTRAINT FK_PARTY_IDENT_PARTY FOREIGN KEY (FK_PARTY) REFERENCES TB_PM_PARTY (ID_PK);

ALTER TABLE TB_PM_PARTY_IDENTIFIER ADD CONSTRAINT FK_PARTY_IDENT_ID_TYPE FOREIGN KEY (FK_PARTY_ID_TYPE) REFERENCES TB_PM_PARTY_ID_TYPE (ID_PK);

CREATE INDEX IDX_FK_PARTY_IDENT_PARTY ON TB_PM_PARTY_IDENTIFIER(FK_PARTY);

CREATE INDEX IDX_FK_PARTY_IDENT_ID_TYPE ON TB_PM_PARTY_IDENTIFIER(FK_PARTY_ID_TYPE);

CREATE TABLE TB_PM_PARTY_IDENTIFIER_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), FK_PARTY NUMBER(38, 0), CONSTRAINT PK_PARTY_IDENTIFIER_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_PM_PARTY_IDENTIFIER_AUD ADD CONSTRAINT FK_PARTY_IDENT_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_PARTY_IDENT_AUD_REV ON TB_PM_PARTY_IDENTIFIER_AUD(REV);

CREATE TABLE TB_PM_PARTY_ID_TYPE_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), NAME VARCHAR2(255), NAME_MOD NUMBER(1), VALUE VARCHAR2(1024), VALUE_MOD NUMBER(1), CONSTRAINT PK_PARTY_ID_TYPE_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_PM_PARTY_ID_TYPE_AUD ADD CONSTRAINT FK_PARTY_ID_TYPE_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_PARTY_ID_TYPE_AUD_REV ON TB_PM_PARTY_ID_TYPE_AUD(REV);

ALTER TABLE TB_PM_PAYLOAD_PROFILE ADD CONSTRAINT FK_PAYLOAD_PROFILE_BP FOREIGN KEY (FK_BUSINESSPROCESS) REFERENCES TB_PM_BUSINESS_PROCESS (ID_PK);

CREATE INDEX IDX_FK_PAYLOAD_PROFILE_BP ON TB_PM_PAYLOAD_PROFILE(FK_BUSINESSPROCESS);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-Alert Tables::Cosmin Baciu
CREATE TABLE TB_ALERT (ID_PK NUMBER(38, 0) NOT NULL, ALERT_TYPE VARCHAR2(50) NOT NULL, ATTEMPTS_NUMBER INTEGER, MAX_ATTEMPTS_NUMBER INTEGER NOT NULL, PROCESSED NUMBER(1), PROCESSED_TIME TIMESTAMP, REPORTING_TIME TIMESTAMP, REPORTING_TIME_FAILURE TIMESTAMP, NEXT_ATTEMPT TIMESTAMP, FK_TIMEZONE_OFFSET NUMBER(38, 0), ALERT_STATUS VARCHAR2(50) NOT NULL, ALERT_LEVEL VARCHAR2(20) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_ALERT PRIMARY KEY (ID_PK));

ALTER TABLE TB_ALERT ADD CONSTRAINT FK_ALERT_TZ_OFFSET FOREIGN KEY (FK_TIMEZONE_OFFSET) REFERENCES TB_D_TIMEZONE_OFFSET (ID_PK);

CREATE INDEX IDX_ALERT_TZ_OFFSET ON TB_ALERT(FK_TIMEZONE_OFFSET);

CREATE INDEX IDX_ALERT_STATUS ON TB_ALERT(ALERT_STATUS);

CREATE TABLE TB_EVENT (ID_PK NUMBER(38, 0) NOT NULL, EVENT_TYPE VARCHAR2(50) NOT NULL, REPORTING_TIME TIMESTAMP, LAST_ALERT_DATE TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_EVENT PRIMARY KEY (ID_PK));

CREATE TABLE TB_EVENT_ALERT (FK_EVENT NUMBER(38, 0) NOT NULL, FK_ALERT NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_EVENT_ALERT PRIMARY KEY (FK_EVENT, FK_ALERT));

ALTER TABLE TB_EVENT_ALERT ADD CONSTRAINT FK_ALERT_ID FOREIGN KEY (FK_ALERT) REFERENCES TB_ALERT (ID_PK);

ALTER TABLE TB_EVENT_ALERT ADD CONSTRAINT FK_EVENT_ID FOREIGN KEY (FK_EVENT) REFERENCES TB_EVENT (ID_PK);

CREATE INDEX IDX_FK_ALERT ON TB_EVENT_ALERT(FK_ALERT);

CREATE TABLE TB_EVENT_PROPERTY (ID_PK NUMBER(38, 0) NOT NULL, PROPERTY_TYPE VARCHAR2(50) NOT NULL, FK_EVENT NUMBER(38, 0) NOT NULL, DTYPE VARCHAR2(31), STRING_VALUE VARCHAR2(255), DATE_VALUE TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_EVENT_PROPERTY PRIMARY KEY (ID_PK));

ALTER TABLE TB_EVENT_PROPERTY ADD CONSTRAINT FK_EVENT_PROPERTY_ID FOREIGN KEY (FK_EVENT) REFERENCES TB_EVENT (ID_PK);

CREATE INDEX IDX_FK_EVENT_PROPERTY ON TB_EVENT_PROPERTY(FK_EVENT);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-8450::Francois Gautier
CREATE TABLE TB_EARCHIVE_BATCH (ID_PK NUMBER(38, 0) NOT NULL, BATCH_ID VARCHAR2(255), ORIGINAL_BATCH_ID VARCHAR2(255), REEXPORTED NUMBER(1) DEFAULT 0 NOT NULL, REQUEST_TYPE VARCHAR2(255), BATCH_STATUS VARCHAR2(255), DATE_REQUESTED TIMESTAMP, LAST_PK_USER_MESSAGE NUMBER(38, 0), FIRST_PK_USER_MESSAGE NUMBER(38, 0), DOMIBUS_CODE VARCHAR2(255), MESSAGE VARCHAR2(255), MANIFEST_CHECK_SUM VARCHAR2(255), BATCH_SIZE INTEGER, STORAGE_LOCATION VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_EARCHIVE_BATCH PRIMARY KEY (ID_PK));

COMMENT ON COLUMN TB_EARCHIVE_BATCH.ORIGINAL_BATCH_ID IS 'The original BATCH_ID from which this batch was generated/re-exported';

COMMENT ON COLUMN TB_EARCHIVE_BATCH.REEXPORTED IS 'true if this batch messages were re-exported by a new batch';

CREATE UNIQUE INDEX IDX_EARCHIVE_BATCH_UNIQUE_ID ON TB_EARCHIVE_BATCH(BATCH_ID);

CREATE INDEX IDX_EARCHIVE_BATCH_STATUS ON TB_EARCHIVE_BATCH(BATCH_STATUS);

CREATE TABLE TB_EARCHIVEBATCH_UM (ID_PK NUMBER(38, 0) NOT NULL, FK_EARCHIVE_BATCH_ID NUMBER(38, 0) NOT NULL, FK_USER_MESSAGE_ID NUMBER(38, 0) NOT NULL, MESSAGE_ID VARCHAR2(255) NOT NULL, CONSTRAINT PK_EARCHIVEBATCH_UML PRIMARY KEY (ID_PK));

ALTER TABLE TB_EARCHIVEBATCH_UM ADD CONSTRAINT FK_EARCHIVE_BATCH_ID_FTR FOREIGN KEY (FK_EARCHIVE_BATCH_ID) REFERENCES TB_EARCHIVE_BATCH (ID_PK) ON DELETE CASCADE;

CREATE INDEX IDX_TB_EARCHIVEBATCH_UM_ID ON TB_EARCHIVEBATCH_UM(FK_USER_MESSAGE_ID);

CREATE INDEX IDX_TB_EARCHIVEBATCH_UM_B_ID ON TB_EARCHIVEBATCH_UM(FK_EARCHIVE_BATCH_ID);

CREATE TABLE TB_EARCHIVE_START (ID_PK NUMBER(38, 0) NOT NULL, LAST_PK_USER_MESSAGE NUMBER(38, 0), DESCRIPTION VARCHAR2(255), CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_EARCHIVE_START PRIMARY KEY (ID_PK));

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-Backend Filter Tables::Cosmin Baciu
CREATE TABLE TB_BACKEND_FILTER (ID_PK NUMBER(38, 0) NOT NULL, BACKEND_NAME VARCHAR2(255), PRIORITY INTEGER, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_BACKEND_FILTER PRIMARY KEY (ID_PK));

CREATE TABLE TB_BACKEND_FILTER_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), BACKEND_NAME VARCHAR2(255), BACKENDNAME_MOD NUMBER(1), PRIORITY INTEGER, INDEX_MOD NUMBER(1), ROUTINGCRITERIAS_MOD NUMBER(1), CONSTRAINT PK_BACKEND_FILTER_AUD PRIMARY KEY (ID_PK, REV));

CREATE INDEX IDX_FK_BACKEND_FTR_AUD_REV ON TB_BACKEND_FILTER_AUD(REV);

ALTER TABLE TB_BACKEND_FILTER_AUD ADD CONSTRAINT FK_BACKEND_FILTER_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE TABLE TB_ROUTING_CRITERIA (ID_PK NUMBER(38, 0) NOT NULL, EXPRESSION VARCHAR2(255), NAME VARCHAR2(255), FK_BACKEND_FILTER NUMBER(38, 0), PRIORITY INTEGER, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_ROUTING_CRITERIA PRIMARY KEY (ID_PK));

ALTER TABLE TB_ROUTING_CRITERIA ADD CONSTRAINT FK_ROUT_CRIT_BACK_FTR FOREIGN KEY (FK_BACKEND_FILTER) REFERENCES TB_BACKEND_FILTER (ID_PK);

CREATE INDEX IDX_FK_ROUT_CRIT_BACK_FTR ON TB_ROUTING_CRITERIA(FK_BACKEND_FILTER);

CREATE TABLE TB_ROUTING_CRITERIA_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), EXPRESSION VARCHAR2(255), EXPRESSION_MOD NUMBER(1), NAME VARCHAR2(255), NAME_MOD NUMBER(1), CONSTRAINT PK_ROUTING_CRITERIA_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_ROUTING_CRITERIA_AUD ADD CONSTRAINT FK_ROUT_CRIT_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_ROUT_CRIT_AUD_REV ON TB_ROUTING_CRITERIA_AUD(REV);

CREATE TABLE TB_BACK_RCRITERIA_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), FK_BACKEND_FILTER NUMBER(38, 0), PRIORITY INTEGER, CONSTRAINT PK_BACK_RCRITERIA_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_BACK_RCRITERIA_AUD ADD CONSTRAINT FK_BCK_RCR_AUD_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_BCK_RCR_AUD_REV_INFO ON TB_BACK_RCRITERIA_AUD(REV);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-7803-User/Plugin User Tables::Cosmin Baciu
CREATE TABLE TB_AUTHENTICATION_ENTRY (ID_PK NUMBER(38, 0) NOT NULL, CERTIFICATE_ID VARCHAR2(255), USERNAME VARCHAR2(255), PASSWD VARCHAR2(255), AUTH_ROLES VARCHAR2(255) NOT NULL, ORIGINAL_USER VARCHAR2(255), BACKEND VARCHAR2(255), PASSWORD_CHANGE_DATE TIMESTAMP, DEFAULT_PASSWORD NUMBER(1) DEFAULT 0, ATTEMPT_COUNT INTEGER DEFAULT 0 NOT NULL, SUSPENSION_DATE TIMESTAMP, USER_ENABLED NUMBER(1) DEFAULT 1 NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_AUTHENTICATION_ENTRY PRIMARY KEY (ID_PK));

ALTER TABLE TB_AUTHENTICATION_ENTRY ADD CONSTRAINT UK_PLUGIN_USER_NAME UNIQUE (USERNAME);

ALTER TABLE TB_AUTHENTICATION_ENTRY ADD CONSTRAINT UK_PLUGIN_USER_CERT UNIQUE (CERTIFICATE_ID);

CREATE TABLE TB_AUTHENTICATION_ENTRY_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), CERTIFICATE_ID VARCHAR2(255), CERTIFICATEID_MOD NUMBER(1), USERNAME VARCHAR2(255), USERNAME_MOD NUMBER(1), PASSWD VARCHAR2(255), PASSWORD_MOD NUMBER(1), AUTH_ROLES VARCHAR2(255), AUTHROLES_MOD NUMBER(1), ORIGINAL_USER VARCHAR2(255), ORIGINALUSER_MOD NUMBER(1), BACKEND VARCHAR2(255), BACKEND_MOD NUMBER(1), USER_ENABLED NUMBER(1), ACTIVE_MOD NUMBER(1), PASSWORD_CHANGE_DATE TIMESTAMP, PASSWORDCHANGEDATE_MOD NUMBER(1), DEFAULT_PASSWORD NUMBER(1), DEFAULTPASSWORD_MOD NUMBER(1), CONSTRAINT PK_AUTHENTICATION_ENTRY_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_AUTHENTICATION_ENTRY_AUD ADD CONSTRAINT FK_AUTH_ENTRY_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_AUTH_ENTRY_AUD_REV ON TB_AUTHENTICATION_ENTRY_AUD(REV);

CREATE TABLE TB_PLUGIN_USER_PASSWD_HISTORY (ID_PK NUMBER(38, 0) NOT NULL, USER_ID NUMBER(38, 0) NOT NULL, USER_PASSWORD VARCHAR2(255) NOT NULL, PASSWORD_CHANGE_DATE TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PLUGIN_USER_PASSWD_HISTO PRIMARY KEY (ID_PK));

ALTER TABLE TB_PLUGIN_USER_PASSWD_HISTORY ADD CONSTRAINT FK_PLUGIN_USER_PASSWD_HISTORY FOREIGN KEY (USER_ID) REFERENCES TB_AUTHENTICATION_ENTRY (ID_PK);

CREATE INDEX IDX_PLUGIN_USER_ID ON TB_PLUGIN_USER_PASSWD_HISTORY(USER_ID);

CREATE TABLE TB_USER (ID_PK NUMBER(38, 0) NOT NULL, USER_EMAIL VARCHAR2(255), USER_ENABLED NUMBER(1) NOT NULL, USER_PASSWORD VARCHAR2(255) NOT NULL, USER_NAME VARCHAR2(255) NOT NULL, OPTLOCK INTEGER, ATTEMPT_COUNT INTEGER DEFAULT 0, SUSPENSION_DATE TIMESTAMP, USER_DELETED NUMBER(1) DEFAULT 0 NOT NULL, PASSWORD_CHANGE_DATE TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, DEFAULT_PASSWORD NUMBER(1) DEFAULT 0, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_USER PRIMARY KEY (ID_PK));

ALTER TABLE TB_USER ADD CONSTRAINT UK_USER_NAME UNIQUE (USER_NAME);

CREATE TABLE TB_USER_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), USER_ENABLED NUMBER(1), ACTIVE_MOD NUMBER(1), USER_DELETED NUMBER(1), DELETED_MOD NUMBER(1), USER_EMAIL VARCHAR2(255), EMAIL_MOD NUMBER(1), USER_PASSWORD VARCHAR2(255), PASSWORD_MOD NUMBER(1), USER_NAME VARCHAR2(255), USERNAME_MOD NUMBER(1), OPTLOCK INTEGER, VERSION_MOD NUMBER(1), ROLES_MOD NUMBER(1), PASSWORD_CHANGE_DATE TIMESTAMP, PASSWORDCHANGEDATE_MOD NUMBER(1), DEFAULT_PASSWORD NUMBER(1), DEFAULTPASSWORD_MOD NUMBER(1), CONSTRAINT PK_USER_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_USER_AUD ADD CONSTRAINT FK_USER_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_USER_AUD_REV ON TB_USER_AUD(REV);

CREATE TABLE TB_USER_PASSWORD_HISTORY (ID_PK NUMBER(38, 0) NOT NULL, USER_ID NUMBER(38, 0) NOT NULL, USER_PASSWORD VARCHAR2(255) NOT NULL, PASSWORD_CHANGE_DATE TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_USER_PASSWORD_HISTORY PRIMARY KEY (ID_PK));

ALTER TABLE TB_USER_PASSWORD_HISTORY ADD CONSTRAINT FK_USER_PASSWORD_HISTORY FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID_PK);

CREATE INDEX IDX_UPH_USER_ID ON TB_USER_PASSWORD_HISTORY(USER_ID);

CREATE TABLE TB_USER_ROLE (ID_PK NUMBER(38, 0) NOT NULL, ROLE_NAME VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID_PK));

ALTER TABLE TB_USER_ROLE ADD CONSTRAINT UK_ROLE_NAME UNIQUE (ROLE_NAME);

CREATE TABLE TB_USER_ROLES (USER_ID NUMBER(38, 0) NOT NULL, ROLE_ID NUMBER(38, 0) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255));

CREATE INDEX IDX_ROLE_ID ON TB_USER_ROLES(ROLE_ID);

CREATE UNIQUE INDEX IDX_TB_USER_ROLES_USER_ROLE_UK ON TB_USER_ROLES(USER_ID, ROLE_ID);

ALTER TABLE TB_USER_ROLES ADD CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID_PK);

ALTER TABLE TB_USER_ROLES ADD CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (ROLE_ID) REFERENCES TB_USER_ROLE (ID_PK);

CREATE TABLE TB_USER_ROLES_AUD (REV NUMBER(38, 0), REVTYPE NUMBER(3), USER_ID NUMBER(38, 0), ROLE_ID NUMBER(38, 0));

CREATE TABLE TB_USER_ROLE_AUD (ID_PK NUMBER(38, 0) NOT NULL, REV NUMBER(38, 0) NOT NULL, REVTYPE NUMBER(3), ROLE_NAME VARCHAR2(255), NAME_MOD NUMBER(1), USERS_MOD NUMBER(1), CONSTRAINT PK_USER_ROLE_AUD PRIMARY KEY (ID_PK, REV));

ALTER TABLE TB_USER_ROLE_AUD ADD CONSTRAINT FK_USR_ROL_AUD_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID);

CREATE INDEX IDX_FK_USR_ROL_AUD_REV_INFO ON TB_USER_ROLE_AUD(REV);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-4669::dussath
-- Create pull request table
CREATE TABLE TB_PULL_REQUEST (PULL_REQUEST_UUID VARCHAR2(255) NOT NULL, MPC VARCHAR2(255) NOT NULL, CONSTRAINT PK_PULL_REQUEST PRIMARY KEY (PULL_REQUEST_UUID));

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-8503_1::ion perpegel
CREATE TABLE TB_LOCK (ID_PK NUMBER(38, 0) NOT NULL, LOCK_KEY VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_LOCK PRIMARY KEY (ID_PK));

COMMENT ON TABLE TB_LOCK IS 'Stores keys used for locking/synchronizing in cluster';

ALTER TABLE TB_LOCK ADD CONSTRAINT UK_LOCK_KEY UNIQUE (LOCK_KEY);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-8532::ion perpegel
CREATE TABLE TB_TRUSTSTORE (ID_PK NUMBER(38, 0) NOT NULL, NAME VARCHAR2(100) NOT NULL, TYPE VARCHAR2(50) NOT NULL, "PASSWORD" VARCHAR2(100) NOT NULL, CONTENT BLOB NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_TRUSTSTORE PRIMARY KEY (ID_PK));

ALTER TABLE TB_TRUSTSTORE ADD CONSTRAINT UK_NAME UNIQUE (NAME);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-9563::Razvan Cretu
CREATE TABLE TB_PARTY_STATUS (ID_PK NUMBER(38, 0) NOT NULL, PARTY_NAME VARCHAR2(100) NOT NULL, CONNECTIVITY_STATUS VARCHAR2(50) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_PARTY_STATUS PRIMARY KEY (ID_PK));

ALTER TABLE TB_PARTY_STATUS ADD CONSTRAINT UK_PARTY_NAME UNIQUE (PARTY_NAME);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-9686::Lucian Furca
ALTER TABLE TB_PM_SECURITY ADD PROFILE VARCHAR2(255);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-10091::Soumya Chandran 
CREATE TABLE TB_MESSAGES_TO_RESEND (ID_PK NUMBER(38, 0) NOT NULL, MESSAGE_ID VARCHAR2(255) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_MESSAGES_TO_RESEND PRIMARY KEY (ID_PK));

ALTER TABLE TB_MESSAGES_TO_RESEND ADD CONSTRAINT UK_MESSAGE_ID UNIQUE (MESSAGE_ID);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-12066::Cosmin Baciu
CREATE TABLE TB_DDC_LOOKUP (ID_PK NUMBER(38, 0) NOT NULL, FINAL_RECIPIENT VARCHAR2(255), ENDPOINT_URL VARCHAR2(1000), PARTY_NAME VARCHAR2(255) NOT NULL, PARTY_TYPE VARCHAR2(255) NOT NULL, PARTY_PROCESSES VARCHAR2(500) NOT NULL, CERT_ISSUER_SUBJECT VARCHAR2(500) NOT NULL, CERT_CN VARCHAR2(255) NOT NULL, CERT_SUBJECT VARCHAR2(255) NOT NULL, CERT_SERIAL VARCHAR2(255) NOT NULL, CERT_FINGERPRINT VARCHAR2(255) NOT NULL, DDC_LOOKUP_TIME TIMESTAMP, CREATION_TIME TIMESTAMP DEFAULT SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR2(255) DEFAULT user NOT NULL, MODIFICATION_TIME TIMESTAMP, MODIFIED_BY VARCHAR2(255), CONSTRAINT PK_DDC_CERTIFICATE PRIMARY KEY (ID_PK));

ALTER TABLE TB_DDC_LOOKUP ADD CONSTRAINT UK_DDC_FINAL_RECIPIENT UNIQUE (FINAL_RECIPIENT);

CREATE INDEX IDX_DDC_PARTY_NAME ON TB_DDC_LOOKUP(PARTY_NAME);

CREATE INDEX IDX_DDC_CERT_CN ON TB_DDC_LOOKUP(CERT_CN);

CREATE INDEX IDX_DDC_DDC_LOOKUP_TIME ON TB_DDC_LOOKUP(DDC_LOOKUP_TIME);

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-11796-add-pks-oracle::Gabriel Maier
ALTER TABLE TB_COMMAND_PROPERTY
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_COMMAND_PROPERTY
                ADD CONSTRAINT PK_TB_COMMAND_PROPERTY PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_PM_JOIN_PAYLOAD_PROFILE
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_PM_JOIN_PAYLOAD_PROFILE
                ADD CONSTRAINT PK_TB_PM_JOIN_PAYLOAD_PROFILE PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_INIT_PARTY
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_INIT_PARTY
                ADD CONSTRAINT PK_TB_PM_JOIN_PROCESS_INIT_PARTY PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_LEG
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_LEG
                ADD CONSTRAINT PK_TB_PM_JOIN_PROCESS_LEG PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_RESP_PARTY
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_PM_JOIN_PROCESS_RESP_PARTY
                ADD CONSTRAINT PK_TB_PM_JOIN_PROCESS_RESP_PARTY PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_PM_JOIN_PROPERTY_SET
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_PM_JOIN_PROPERTY_SET
                ADD CONSTRAINT PK_TB_PM_JOIN_PROPERTY_SET PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_USER_ROLES
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_USER_ROLES
                ADD CONSTRAINT PK_TB_USER_ROLES PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_VERSION
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_VERSION
                ADD CONSTRAINT PK_TB_VERSION PRIMARY KEY (ID_PK)
            /
            ALTER TABLE TB_USER_ROLES_AUD
                ADD ID_PK NUMBER(38, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY
            /
            ALTER TABLE TB_USER_ROLES_AUD
                ADD CONSTRAINT PK_TB_USER_ROLES_AUD PRIMARY KEY (ID_PK)
/

-- Changeset src/main/resources/db/releases/5.1.9/5.1.9-changelog.xml::EDELIVERY-14338::perpeio
CREATE OR REPLACE PROCEDURE LOCK_MESSAGE_SKIP_BLOCKED (
                p_MPC IN NVARCHAR2,
                p_INITIATOR IN NVARCHAR2,
                p_CURRENT_TIMESTAMP IN DATE,
                p_ROW OUT SYS_REFCURSOR
            ) IS
                CURSOR c_1 IS
                    SELECT /*+FIRST_ROWS_1*/ ml.*
                    FROM TB_MESSAGING_LOCK ml
                    WHERE ml.MESSAGE_STATE='READY'
                      AND ml.MPC=p_MPC
                      AND ml.INITIATOR=p_INITIATOR
                      AND ml.MESSAGE_TYPE='PULL'
                      AND ml.NEXT_ATTEMPT < p_CURRENT_TIMESTAMP
                      AND ml.MESSAGE_STALED > p_CURRENT_TIMESTAMP
                    ORDER BY ID_PK
                        FOR UPDATE SKIP LOCKED;

                v_row TB_MESSAGING_LOCK%ROWTYPE;

            BEGIN
                OPEN c_1;
                FETCH c_1 INTO v_row;
                IF c_1%FOUND THEN
                    OPEN p_row FOR SELECT * FROM TB_MESSAGING_LOCK WHERE ID_PK = v_row.ID_PK;
                ELSE
                    OPEN p_row FOR SELECT NULL FROM DUAL WHERE 1=0;
                END IF;
                CLOSE c_1;
            END LOCK_MESSAGE_SKIP_BLOCKED;
/
