services:
  # 1. SIMULATED PRODUCTION DATABASE
  domibus_prod_db:
    image: gvenzl/oracle-free:latest
    container_name: domibus_prod_db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=ProdSysPass123
    volumes:
      # Relative to where docker-compose.yml lives (inside docker/ folder)
      - ./scripts:/container-entrypoint-initdb.d
    restart: always

  # 2. ANONYMIZATION SANDBOX DATABASE
  domibus_anon_db:
    image: gvenzl/oracle-free:latest
    container_name: domibus_anon_db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=AnonSysPass123
    # No volumes here, it starts fresh and receives data via impdp
    restart: always