services:
  # 1. PRODUCTION DATABASE
  domibus_prod_db:
    image: gvenzl/oracle-free:latest
    container_name: domibus_prod_db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=ProdSysPass123
    volumes:
      - ./scripts:/container-entrypoint-initdb.d
    restart: always

  # 2. ANONYMIZATION SANDBOX DATABASE
  domibus_anon_db:
    image: gvenzl/oracle-free:latest
    container_name: domibus_anon_db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=AnonSysPass123
    volumes:
      - ./scripts:/container-entrypoint-initdb.d
      # Maps local exports folder to a reliable, custom directory path
      - ./exports:/opt/oracle/exports
    restart: always